{{- if .Values.kubeletCadvisorPusher.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "chart.fullname" . }}-kubelet-cadvisor-pusher
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app: kubelet-cadvisor-pusher
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: kubelet-cadvisor-pusher
    spec:
      serviceAccountName: {{ include "chart.fullname" . }}-kubelet-cadvisor-pusher
      containers:
        - name: agent
          image: {{ .Values.agent.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: ENABLE_CADVISOR
              value: "true"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CLUSTER
              value: "{{ default .Release.Namespace .Values.agent.labels.cluster }}"
            - name: CUSTOMER_NAME
              value: "{{ default .Release.Namespace .Values.agent.labels.client }}"
            - name: ENV
              value: "{{ .Values.agent.labels.env }}"
            - name: PUSH_INTERVAL
              value: "{{ .Values.agent.cadvisor.pushInterval }}"
            - name: AGENT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "chart.fullname" . }}-agent-basic-auth
                  key: username
            - name: AGENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "chart.fullname" . }}-agent-basic-auth
                  key: password
          resources:
            {{- toYaml .Values.kubeletCadvisorPusher.resources | nindent 12 }}
{{- end }}
