apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "chart.fullname" . }}-node-exporter
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app: node-exporter
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: node-exporter
    spec:
      hostPID: true
      hostNetwork: true
      tolerations:
        - operator: "Exists"
      containers:
        - name: node-exporter
          image: {{ .Values.nodeExporter.image }}
          args:
            - '--path.rootfs=/host'
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$$'
          ports:
            - name: metrics
              containerPort: 9100
          resources:
            {{- toYaml .Values.nodeExporter.resources | nindent 12 }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: rootfs
              mountPath: /host
              readOnly: true
            - name: sysfs
              mountPath: /host/sys
              readOnly: true
            - name: procfs
              mountPath: /host/proc
              readOnly: true
            - name: devfs
              mountPath: /host/dev
              readOnly: true
        - name: agent
          image: {{ .Values.agent.image }}
          env:
            - name: ENABLE_NODE_EXPORTER_K8S
              value: "true"
            - name: SCRAPE_URL
              value: "http://127.0.0.1:9100/metrics"
            - name: INSTANCE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CLUSTER
              value: "{{ default .Release.Namespace .Values.agent.labels.cluster }}"
            - name: CUSTOMER_NAME
              value: "{{ default .Release.Namespace .Values.agent.labels.client }}"
            - name: ENV
              value: "{{ .Values.agent.labels.env }}"
            - name: PUSH_INTERVAL
              value: "{{ .Values.agent.nodeExporter.pushInterval }}"
            - name: AGENT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "chart.fullname" . }}-agent-basic-auth
                  key: username
            - name: AGENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "chart.fullname" . }}-agent-basic-auth
                  key: password
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
      volumes:
        - name: rootfs
          hostPath:
            path: /
            type: Directory
        - name: sysfs
          hostPath:
            path: /sys
            type: Directory
        - name: runfs
          hostPath:
            path: /run
            type: Directory
        - name: procfs
          hostPath:
            path: /proc
            type: Directory
        - name: devfs
          hostPath:
            path: /dev
            type: Directory

