{{- if .Values.rabbitmqMonitoring.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-rabbitmq-monitoring
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app: rabbitmq-monitoring
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: rabbitmq-monitoring
    spec:
      serviceAccountName: {{ include "chart.fullname" . }}-rabbitmq-monitoring
      containers:
        - name: agent
          image: {{ .Values.agent.image }}
          env:
            - name: RABBITMQ_ENDPOINT
              value: "{{ .Values.rabbitmqMonitoring.endpoint }}"
            {{- if .Values.rabbitmqMonitoring.excludedQueues }}
            - name: RABBITMQ_EXCLUDED_QUEUES
              value: "{{ .Values.rabbitmqMonitoring.excludedQueues }}"
            {{- end }}
            - name: PUSH_INTERVAL
              value: "{{ .Values.agent.rabbitmqMonitoring.pushInterval }}"
            - name: INSTANCE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER
              value: "{{ default .Release.Namespace .Values.agent.labels.cluster }}"
            - name: ENV
              value: "{{ .Values.agent.labels.env }}"
            - name: CUSTOMER_NAME
              value: "{{ default .Release.Namespace .Values.agent.labels.client }}"
            - name: AGENT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "chart.fullname" . }}-agent-basic-auth
                  key: username
            - name: AGENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "chart.fullname" . }}-agent-basic-auth
                  key: password
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
{{- end }}
