{{- if .Values.rabbitmqMonitoring.enabled }}
apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "chart.fullname" . }}-rabbitmq-monitoring
  labels:
    {{- include "chart.labels" . | nindent 4 }}
{{- end }}
