{{- if .Values.databaseMonitoring.enabled }}
apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "chart.fullname" . }}-database-monitoring
  labels:
    {{- include "chart.labels" . | nindent 4 }}
{{- end }}
