# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

agent:
  image: "ghcr.io/matvi-consulting/monitoring-agent-docker:1.0.9"
  url: "https://push.prod.matvi-consulting.com"   # sans le suffixe /metrics
  basicAuth:
    username: ""
    password: ""

  # Grouping labels ajoutées au chemin Pushgateway
  labels:
    # par défaut, on injectera .Release.Namespace au runtime si 'cluster' est vide
    cluster: ""
    env: ""
    client: ""
  resources:
    requests: { cpu: 20m, memory: 32Mi }
    limits:   { cpu: 100m, memory: 64Mi }
  nodeExporter:
    pushInterval: 15
  cadvisor:
    pushInterval: 0
  kubeStateMetrics:
    pushInterval: 0

nodeExporter:
  image: "quay.io/prometheus/node-exporter:v1.9.1"
  resources:
    requests: { cpu: 50m, memory: 64Mi }
    limits:   { cpu: 200m, memory: 128Mi }

kubeStateMetrics:
  image: "registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.17.0"
  replicas: 1
  resources:
    requests: { cpu: 50m, memory: 128Mi }
    limits:   { cpu: 200m, memory: 256Mi }

kubeletCadvisorPusher:
  enabled: true
  resources:
    requests: { cpu: 20m, memory: 32Mi }
    limits:   { cpu: 100m, memory: 64Mi }
  filters:
    include: []   # e.g. ['^(container_cpu_|container_memory_)']
    exclude: []   # e.g. ['^container_network_.*']

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
